### PR TITLE
feat: add flight id and game client versions to log

### PR DESCRIPTION
**Pull request by medreza**
Add new fields to access log. Here is the go version: https://github.com/AccelByte/go-restful-plugins/pull/73/files

### CODE REVIEW

**Comment by medreza** [comment]
hi @AdityaDerrySaputra @ghiffari-agsarya @NurFaizin please help to review this PR. Thanks

**Review by NurFaizin — APPROVED** [review]
LGTM

**Review by ghiffari-agsarya — APPROVED** [review]
Approved

**Comment by medreza** [comment]
Hi @NurFaizin @ghiffari-agsarya, please help to merge it since I don't have the permission. Thanks!

**Pull request merged**
